import json, sys
sys.stdout.reconfigure(encoding='utf-8')

planning_content = (
"## PROJECT STATUS, RESEARCH LANDSCAPE & ROADMAP TO PUBLICATION\n"
"### QHSA-Net: Quantum Hybrid Spectral-Attention Network\n"
"\n"
"> **Written:** March 2026 | **Purpose:** Comprehensive project review, competitive analysis, and step-by-step publication roadmap for a conference paper + journal extension.\n"
"\n"
"---\n"
"\n"
"## PART 1 — WHAT WE BUILT (Project Summary)\n"
"\n"
"### 1.1 Architecture Overview\n"
"\n"
"We designed **QHSA-Net** (Quantum Hybrid Spectral-Attention Network), a dual-branch hybrid quantum-classical architecture for pixel-wise hyperspectral image (HSI) classification on the **Pavia University** dataset (610×340×103 bands, 9 land-cover classes, 42,776 labeled pixels).\n"
"\n"
"**The two branches:**\n"
"\n"
"| Branch | Technology | Input | Output |\n"
"|---|---|---|---|\n"
"| Classical Spatial Encoder | 3D-CNN → 2D-CNN → AvgPool | 9×9×103 HSI patch | F_classical ∈ ℝ⁶⁴ |\n"
"| Quantum Spectral Attention (VQSAC) | PennyLane VQC (8 qubits, 2 layers) | 8 PCA features | F_quantum ∈ ℝ⁶⁴ |\n"
"\n"
"These are fused via a **learnable gating mechanism**: α = σ(MLP([F_c, F_q])), then F_fused = α·F_q + (1−α)·F_c, followed by a 2-layer MLP classifier.\n"
"\n"
"**The quantum circuit (VQSAC):**\n"
"- **Input:** 8 PCA-compressed spectral features (PCA retains 99.81% of spectral variance, reducing 103 bands → 8 components)\n"
"- **Encoding:** AngleEmbedding — each feature becomes a Y-rotation angle on one qubit: angle = sigmoid(x) × π ∈ [0, π]\n"
"- **Ansatz:** StronglyEntanglingLayers × 2 (ring CNOT topology + RX/RY/RZ per qubit) = **48 trainable quantum parameters total**\n"
"- **Measurement:** PauliZ expectation per qubit → 8 values in [−1, +1] = learned spectral attention scores per PCA mode\n"
"- **Projection:** Linear(8→64) + LayerNorm + GELU\n"
"\n"
"**Training configuration:**\n"
"- Dual learning rates: classical lr=1×10⁻³, quantum lr=1×10⁻² (flatter VQC loss landscape requires larger steps)\n"
"- CosineAnnealingLR scheduler over 30 epochs\n"
"- Gradient clipping max_norm=1.0 (barren plateau safety net)\n"
"- `QUICK_RUN=True` during development (~3,000 training samples, NOT the full dataset)\n"
"\n"
"### 1.2 Reported Results (QUICK_RUN — ⚠️ NOT FINAL)\n"
"\n"
"| Model | OA (%) | AA (%) | κ (%) |\n"
"|---|---|---|---|\n"
"| SVM (RBF, 8 PCA features) | 88.54 | 84.95 | 84.61 |\n"
"| HybridSN (3D+2D CNN) | 99.77 | 99.50 | 99.69 |\n"
"| **QHSA-Net [proposed]** | **99.91** | **99.73** | **99.88** |\n"
"\n"
"**⚠️ CRITICAL CAVEAT:** These results were obtained with `QUICK_RUN=True`, which randomly downsamples to ~3,000 of 42,776 labeled pixels and trains for only 30 epochs. These numbers are promising but are **NOT reportable** results. Full training on the complete dataset is required before any submission.\n"
"\n"
"### 1.3 The Six Research Gaps We Claim to Fill\n"
"\n"
"| Gap | Our Solution | Status |\n"
"|---|---|---|\n"
"| G1: No real VQC ever benchmarked on Pavia University | First VQC OA/AA/κ on PU | ✅ Novel (confirmed by 2026 lit search) |\n"
"| G2: Angle encoding needs 103 qubits (NISQ-infeasible) | PCA 103→8, only 8 qubits needed | ✅ Implemented |\n"
"| G3: Quantum attention targets spatial tokens only | Quantum Spectral Attention (band importance) | ✅ Novel |\n"
"| G4: No quantum-classical gated fusion for HSI | Learnable α-weighted gated fusion | ✅ Implemented |\n"
"| G5: Barren plateaus unaddressed in quantum HSI lit | Shallow VQC + local PauliZ + grad clip | ✅ Addressed |\n"
"| G6: No low-label VQC benchmark on Pavia University | 1%/3%/5%/10% label experiments | ⚠️ Partial (needs full runs) |\n"
"\n"
"### 1.4 Ablation Variants Implemented\n"
"\n"
"| Variant | Description | Purpose |\n"
"|---|---|---|\n"
"| V1: No Quantum | Classical 3D-CNN only, quantum branch removed | Isolates value of quantum branch |\n"
"| V2: Cat Fusion | Quantum + classical, simple concatenation, no gate | Validates gating over naive concat |\n"
"| V3: Full QHSA-Net | Gated α-weighted fusion (proposed) | Full model |\n"
"\n"
"---\n"
"\n"
"## PART 2 — CURRENT RESEARCH LANDSCAPE (March 2026)\n"
"\n"
"### 2.1 State-of-the-Art on Pavia University\n"
"\n"
"| Method | OA (%) | Type | Venue / Year |\n"
"|---|---|---|---|\n"
"| DiffusionAAE | **99.56** | Diffusion model + autoencoder | ScienceDirect, 2025 |\n"
"| SDMamba | 99.14 | Mamba state-space model | 2025 |\n"
"| HyperspectralMamba | 98.60 | Mamba SSM | MDPI Remote Sensing, 2025 |\n"
"| HybridSN (Roy 2020) | 98.40 | 3D+2D CNN | IEEE TGRS 2020 |\n"
"| S2Mamba | 97.81 | Spatial-spectral SSM | arXiv, 2024 |\n"
"| SSFTT (Sun 2022) | 97.80 | CNN + Transformer | IEEE TGRS 2022 |\n"
"| SpectralFormer (Hong 2022) | 96.10 | Transformer | IEEE TGRS 2022 |\n"
"| QSSPN (Zhang 2023, quantum-*inspired*) | ~96.40 AA | Quantum-inspired classical | CVPR 2023 |\n"
"| **QHSA-Net [ours, quick run]** | **~99.91** | **Real VQC hybrid** | This work |\n"
"\n"
"**Key observation:** The classical SOTA ceiling is ~99.56% OA (DiffusionAAE, 2025). Our quick-run result is above this, but the full-dataset result is what determines viability. Even if QHSA-Net lands at 99.0–99.5% on the full dataset, the \"first real VQC\" framing remains valid — OA alone is not the only novelty axis.\n"
"\n"
"### 2.2 Key Competing Papers We Must Cite and Differentiate\n"
"\n"
"**QSSPN — CVPR 2023 (Zhang, Zhou et al.) [MOST IMPORTANT]**\n"
"- Quantum-*inspired* Spectral-Spatial Pyramid Network. Uses quantum mechanics *mathematics* (superposition/measurement analogies) inside a classical CNN. No quantum gates, no qubits — runs entirely on classical hardware.\n"
"- PU OA ~96.40% AA. Our method uses a true VQC and must explicitly clarify this distinction.\n"
"- Reviewers will cite this first. Be ready to respond.\n"
"\n"
"**QUEEN — IEEE TGRS 2024 (Lin et al., Taiwan)**\n"
"- Quantum GNN for hyperspectral *change detection* (not classification). Uses unitary computing features + graph learning.\n"
"- Published in our primary target journal. Need to cite, differentiate by task (change detection vs. classification).\n"
"\n"
"**HyperKING — IEEE TGRS 2025 (Lin et al.) [arXiv:2504.11782]**\n"
"- Quantum-classical GAN for HSI *restoration* (denoising, super-resolution). First quantum GAN for 128×128 HSI.\n"
"- Same target journal. Demonstrates IEEE TGRS welcomes quantum HSI papers.\n"
"\n"
"**QSCDNet — IEEE TQE 2025 (Lv et al.)**\n"
"- Hybrid quantum spectral change detection network. Published in IEEE Transactions on Quantum Engineering — an alternative venue for us.\n"
"\n"
"**HQSAN — Journal of Supercomputing 2025**\n"
"- Hybrid quantum self-attention for *scene classification* (not pixel-wise HSI classification). Amplitude + angle encoding + quantum self-attention. Results: PatternNet 98.09%, RSI-CB256 98.57%.\n"
"- Architecturally most similar to QHSA-Net. Critical difference: we do **pixel-wise** HSI classification on the standard Pavia University benchmark (harder, more established); HQSAN does scene-level (coarser task, non-standard benchmarks).\n"
"\n"
"**HQViT — arXiv:2504.02730 (April 2025)**\n"
"- Hybrid quantum vision transformer. Not applied to HSI. No standard HSI benchmark results.\n"
"\n"
"### 2.3 THE CRITICAL DISTINCTION: True VQC vs. Quantum-Inspired\n"
"\n"
"This is the single most important conceptual issue for reviewers in 2025–2026:\n"
"\n"
"| | Quantum-Inspired (e.g., QSSPN) | True VQC (e.g., QHSA-Net) |\n"
"|---|---|---|\n"
"| Hardware | Classical CPU/GPU only | Quantum simulator or real QPU |\n"
"| Gates | None — uses matrix math inspired by QM | Real quantum gates: Hadamard, CNOT, Rx/Ry/Rz |\n"
"| Parameters | Standard neural net weights | Quantum rotation angles on qubits |\n"
"| Gradients | Standard backprop | Parameter-shift rule (quantum-native) |\n"
"| Hilbert space | Simulated conceptually | Actual 2^n-dimensional quantum state space |\n"
"\n"
"QHSA-Net uses PennyLane's `default.qubit` device, which faithfully simulates quantum gate operations and computes gradients via the parameter-shift rule. This is a **true VQC**, not a quantum-inspired approximation. Our paper must state this explicitly in the Introduction.\n"
"\n"
"### 2.4 Target Publication Venues\n"
"\n"
"| Venue | Type | Tier | Rationale |\n"
"|---|---|---|---|\n"
"| **IEEE TGRS** | Journal | ⭐⭐⭐ Top-tier | Primary target; QUEEN + HyperKING accepted here |\n"
"| **IEEE GRSL** | Letter Journal | ⭐⭐ Strong | Faster, shorter; good for quick first publication |\n"
"| **IEEE TQE** | Journal | ⭐⭐ Emerging | QSCDNet published here; quantum-engineering focus |\n"
"| **IGARSS 2026** | Conference | ⭐⭐ Top RS conf | Stepping stone; check deadline (typically Jan–Feb 2026) |\n"
"| **Quantum (Verein)** | Journal | ⭐⭐ Quantum-specific | QViT published here |\n"
"| **J. Supercomputing** | Journal | ⭐ Mid-tier | HQSAN published here; fallback option |\n"
"\n"
"**Recommended path:** Submit short version to **IGARSS 2026** (if deadline not passed), then extend for **IEEE TGRS** or **IEEE GRSL** journal.\n"
"\n"
"---\n"
"\n"
"## PART 3 — HONEST ASSESSMENT: STRENGTHS & WEAKNESSES\n"
"\n"
"### Strengths ✅\n"
"\n"
"1. **G1 is real and documented.** No peer-reviewed paper has reported true VQC results on Pavia University. Confirmed by an exhaustive March 2026 literature search. The \"first\" claim is defensible.\n"
"2. **Architecture is principled.** Every design choice (PCA compression, angle embedding, shallow VQC, gated fusion, local PauliZ measurements) is individually justified and rooted in NISQ constraints and barren plateau theory.\n"
"3. **Comprehensive evaluation framework.** OA/AA/κ, confusion matrices, t-SNE, attention heatmaps, ablation study, data efficiency curves — more thorough than most quantum HSI papers.\n"
"4. **Barren plateau awareness is genuine novelty.** No prior quantum HSI paper explicitly addresses this. Depth-2 VQC + local measurements + gradient clipping is a real design contribution.\n"
"5. **Clean PennyLane integration.** TorchLayer wrapping, dual learning rates, and parameter-shift gradients are implemented correctly and reproducible.\n"
"\n"
"### Weaknesses ❌ (Must Fix Before Submission)\n"
"\n"
"1. **`QUICK_RUN=True` — results are not final.** Only ~3,000 of 42,776 labeled pixels used. Full dataset training is mandatory before submission.\n"
"2. **Single dataset.** IEEE TGRS almost always requires 2–3 datasets. Indian Pines is the minimum addition.\n"
"3. **No statistical significance.** Single-run results. Need ≥5 seeds, report mean ± std.\n"
"4. **SOTA comparison incomplete.** Missing: DiffusionAAE (99.56%), HyperspectralMamba (98.60%), S2Mamba (97.81%), HQSAN, QUEEN, HQViT.\n"
"5. **No parameter-matched classical baseline.** Need to compare VQC branch vs. a classical MLP with the same ~48 parameters. Without this, reviewers will ask \"why quantum over a tiny MLP?\"\n"
"6. **No noise / hardware analysis.** All results use ideal `default.qubit` simulator. At minimum, a depolarizing noise experiment is needed for a journal submission.\n"
"7. **Quick-run result (99.91%) may not hold at full scale.** Be prepared: if full-run OA ends up at 99.0–99.5%, the paper must rely on \"first VQC\" framing as the primary novelty, not absolute OA rank.\n"
"\n"
"---\n"
"\n"
"## PART 4 — PUBLICATION ROADMAP (Step-by-Step)\n"
"\n"
"### Phase 1: Fix the Foundation (Weeks 1–2)\n"
"\n"
"**Step 1.1 — Full training on Pavia University**\n"
"- Set `QUICK_RUN = False` in the notebook\n"
"- Use full 10% train / 90% test stratified split (standard Pavia University protocol)\n"
"- Train for 100–150 epochs with early stopping (patience=15)\n"
"- Record final OA, AA, κ\n"
"- Estimate: ~4–10 hours CPU, ~30–60 min with GPU\n"
"\n"
"**Step 1.2 — Statistical validation (5 seeds)**\n"
"- Run full training with seeds [0, 1, 2, 3, 4]\n"
"- Report: OA = XX.XX ± Y.YY% (mean ± std across seeds)\n"
"- This is mandatory for IEEE TGRS. IGARSS can accept a single run if clearly stated.\n"
"\n"
"**Step 1.3 — Add Indian Pines dataset**\n"
"- Dataset: 145×145×200 bands, 16 classes, 10,249 labeled pixels\n"
"- Source: http://www.ehu.eus/ccwintco/index.php/Hyperspectral_Remote_Sensing_Scenes\n"
"- Same preprocessing: normalize per-band → PCA(8) → 9×9 patches → 10% train / 90% test\n"
"- Run QHSA-Net + all baselines, 5 seeds each\n"
"- Optional: also add Salinas Valley (512×217×204, 16 classes)\n"
"\n"
"**Step 1.4 — Update SOTA comparison table**\n"
"Add these missing papers to Section 11:\n"
"- DiffusionAAE (OA 99.56%, ScienceDirect 2025)\n"
"- HyperspectralMamba (OA 98.60%, MDPI Remote Sensing 2025)\n"
"- S2Mamba (OA 97.81%, arXiv 2024)\n"
"- HQSAN (J. Supercomputing 2025) — note: scene classification, not pixel-wise HSI\n"
"- QUEEN (IEEE TGRS 2024) — note: change detection task\n"
"\n"
"### Phase 2: Strengthen Novelty (Weeks 2–4)\n"
"\n"
"**Step 2.1 — Parameter-matched classical MLP ablation (V4) [MOST IMPORTANT NEW EXPERIMENT]**\n"
"- Design: Replace quantum branch with a classical MLP having exactly 48 parameters\n"
"  - Architecture: Linear(8→6) + GELU + Linear(6→8) ≈ 48 params, followed by Linear(8→64)\n"
"- Train V4 under identical conditions as QHSA-Net\n"
"- If quantum branch outperforms this parameter-equivalent classical baseline, it directly supports the quantum advantage claim\n"
"- This is the single most persuasive experiment for skeptical reviewers\n"
"\n"
"**Step 2.2 — Depolarizing noise experiment**\n"
"- Switch to PennyLane `default.mixed` device\n"
"- Add `qml.DepolarizingChannel(p, wires=i)` after each gate layer\n"
"- Test noise levels: p = [0.001, 0.005, 0.01, 0.02, 0.05]\n"
"- Plot OA vs. noise probability: shows hardware robustness range\n"
"- Provides bridge between simulation-only results and real NISQ hardware feasibility\n"
"\n"
"**Step 2.3 — Complete data efficiency experiment**\n"
"- Run all models (SVM, HybridSN, V1, V2, V3/QHSA-Net) at label fractions [0.01, 0.03, 0.05, 0.10]\n"
"- 5 seeds per fraction per model\n"
"- Plot OA ± std vs. label fraction curves\n"
"- Key hypothesis: QHSA-Net shows smaller performance degradation at low label fractions, supported by the larger effective Hilbert space providing richer feature representations per sample\n"
"\n"
"**Step 2.4 — Expanded ablation variants**\n"
"- V5: 4 / 6 / **8** / 10 qubits — shows 8 is the optimal qubit count\n"
"- V6: 1 / **2** / 3 VQC layers — validates the depth-2 shallow design choice\n"
"- V7: PCA to 4 / 6 / **8** / 12 components — validates the 8-component choice\n"
"- V8: Different fusion strategies (sum, product, bilinear, cross-attention) vs. gated α-weighting\n"
"\n"
"**Step 2.5 — Enhanced quantum attention analysis**\n"
"- Compute mutual information I(qubit_k; class_label) for each of the 8 qubits across all 9 classes\n"
"- Show which PCA spectral modes the VQC learns to be discriminative per class\n"
"- Makes the \"quantum spectral attention\" claim concrete, verifiable, and interpretable\n"
"\n"
"### Phase 3: Write the Paper (Weeks 4–6)\n"
"\n"
"**Conference version (IGARSS 2026) — 4 pages**\n"
"1. Introduction: motivation, G1 gap, main contribution\n"
"2. QHSA-Net Architecture: VQC circuit diagram, dual-branch design, gated fusion\n"
"3. Experiments: Pavia University results table (5 seeds), ablation V1–V3\n"
"4. Conclusion\n"
"\n"
"**Journal version (IEEE TGRS) — 12–14 pages**\n"
"1. Introduction: all 6 gaps, all 6 contributions, true-VQC distinction\n"
"2. Related Work: classical HSI → quantum-inspired HSI → true VQC works → quantum attention mechanisms\n"
"3. Methodology: VQSAC circuit derivation, classical branch, gated fusion, training strategy, barren plateau mitigation\n"
"4. Experiments: Pavia University + Indian Pines, full SOTA comparison, 5 seeds mean±std\n"
"5. Ablation: V1–V8\n"
"6. Feature Analysis: t-SNE, attention maps, mutual information, quantum-classical complementarity\n"
"7. Data Efficiency: 1%/3%/5%/10% low-label regime curves\n"
"8. Noise Analysis: depolarizing noise experiments, hardware feasibility discussion\n"
"9. Discussion: limitations, hardware deployment roadmap, when quantum helps vs. hurts\n"
"10. Conclusion\n"
"\n"
"### Phase 4: Pre-Submission Checklist\n"
"\n"
"- [ ] Full-dataset training on Pavia University (QUICK_RUN=False) completed\n"
"- [ ] 5-seed statistical validation (mean ± std for all metrics)\n"
"- [ ] Indian Pines results included (minimum for journal)\n"
"- [ ] SOTA table includes 2024–2025 papers (DiffusionAAE, HyperspectralMamba, HQSAN, QUEEN)\n"
"- [ ] HQSAN, QSSPN, QUEEN, HQViT all cited and differentiated from our approach\n"
"- [ ] V4 ablation (param-matched classical MLP) added and discussed\n"
"- [ ] Depolarizing noise experiment completed\n"
"- [ ] Data efficiency curves completed (all fractions, 5 seeds each)\n"
"- [ ] True VQC vs. quantum-inspired distinction explicit in Introduction\n"
"- [ ] All figures at 300+ DPI, proper axis labels, consistent color scheme\n"
"- [ ] BibTeX entries verified for all cited papers\n"
"\n"
"---\n"
"\n"
"## PART 5 — BACKUP NOVELTY ANGLES\n"
"\n"
"If full-run OA results are less competitive than expected, these angles can supplement or reframe the paper:\n"
"\n"
"**Angle A — Multi-Dataset Benchmark Suite**\n"
"Run on PU + Indian Pines + Salinas. Frame as \"the first systematic VQC benchmark across the three canonical HSI datasets.\" The benchmark contribution stands regardless of absolute OA rank.\n"
"\n"
"**Angle B — Quantum-Classical Knowledge Distillation**\n"
"Train QHSA-Net, then distill its learned quantum spectral attention patterns into a lightweight classical student network. Novel framing: quantum training improves a classically deployable inference model. No quantum hardware needed at inference time.\n"
"\n"
"**Angle C — Cross-Dataset Generalization**\n"
"Train on Pavia University, test directly on Indian Pines (zero-shot transfer, no fine-tuning). Hypothesis: quantum Hilbert space features may generalize better across sensor/scene domains. No paper has tested VQC cross-dataset transfer for HSI.\n"
"\n"
"**Angle D — Quantum Kernel Spectral Attention**\n"
"Replace PauliZ measurements with a quantum kernel K(x_i, x_j) = |⟨ψ(x_i)|ψ(x_j)⟩|². Connected to Nature Photonics 2025 results showing quantum kernels outperform classical Gaussian/NTK kernels for some classification tasks.\n"
"\n"
"---\n"
"\n"
"## PART 6 — RISK TABLE\n"
"\n"
"| Risk | Probability | Impact | Mitigation |\n"
"|---|---|---|---|\n"
"| Full-run OA < HybridSN | Medium | High | Reframe: \"first VQC\" is primary claim, not best OA |\n"
"| Reviewer: \"quantum-inspired is sufficient\" | High | Medium | V4 ablation (param-matched MLP) directly answers this |\n"
"| Reviewer: \"only one dataset\" | High | High | Add Indian Pines (Phase 1.3) |\n"
"| Reviewer: \"simulator results not meaningful\" | Medium | Medium | Depolarizing noise experiment (Phase 2.2) |\n"
"| Training time too slow for multi-dataset | High | Medium | Use PennyLane `lightning.qubit` backend (GPU-accelerated) |\n"
"| QUICK_RUN results unreproducible at full scale | Low–Medium | Very High | Run full training ASAP — this is the highest-priority action |\n"
"| IGARSS 2026 deadline already passed | Check | High | Deadline typically Jan–Feb 2026; if missed, target IGARSS 2027 or IEEE GRSL |\n"
"\n"
"---\n"
"\n"
"## PART 7 — IMMEDIATE ACTION ITEMS (Priority Order)\n"
"\n"
"1. **[CRITICAL] Set `QUICK_RUN=False` and run full Pavia University training.** This is the highest-priority action. Nothing can be submitted without full-dataset results.\n"
"\n"
"2. **[CRITICAL] Run 5 seeds for statistical validation.** Single-run results will not survive IEEE TGRS peer review.\n"
"\n"
"3. **[HIGH] Download Indian Pines, add preprocessing and training pipeline to notebook** as a new section.\n"
"\n"
"4. **[HIGH] Update Section 11 SOTA comparison table** with DiffusionAAE, HyperspectralMamba, HQSAN, QUEEN.\n"
"\n"
"5. **[HIGH] Add V4 ablation** — classical MLP with ~48 parameters replacing the quantum branch. The most important new experiment for reviewer credibility.\n"
"\n"
"6. **[MEDIUM] Implement noise experiment** using `default.mixed` with depolarizing channels.\n"
"\n"
"7. **[MEDIUM] Complete data efficiency curves** with 5 seeds at each label fraction (1%/3%/5%/10%).\n"
"\n"
"8. **[MEDIUM] Enhanced attention visualization** — mutual information I(qubit_k; class) for each qubit.\n"
"\n"
"9. **[LOW] Explore `lightning.qubit` backend** for GPU-accelerated VQC training (significant speedup for multi-dataset runs).\n"
"\n"
"10. **[LOW] Draft Introduction section** while experiments run. Focus on the \"first real VQC on Pavia University\" framing and the six gaps.\n"
"\n"
"---\n"
"\n"
"## PART 8 — KEY REFERENCES TO ADD TO THE PAPER\n"
"\n"
"```bibtex\n"
"% QSSPN — quantum-inspired HSI (MOST IMPORTANT to cite + distinguish from)\n"
"@inproceedings{zhang2023qsspn,\n"
"  title={Quantum-Inspired Spectral-Spatial Pyramid Network for Hyperspectral Image Classification},\n"
"  author={Zhang, Yongshan and Zhou, Yicong and others},\n"
"  booktitle={CVPR},\n"
"  year={2023}\n"
"}\n"
"\n"
"% QUEEN — quantum GNN for HSI change detection (IEEE TGRS 2024)\n"
"@article{lin2024queen,\n"
"  title={Quantum Information-Empowered Graph Neural Network for Hyperspectral Change Detection},\n"
"  author={Lin, Chia-Hsiang and Lin, Tzu-Hsuan and Chanussot, Jocelyn},\n"
"  journal={IEEE Transactions on Geoscience and Remote Sensing},\n"
"  year={2024},\n"
"  doi={10.1109/TGRS.2024.3490703}\n"
"}\n"
"\n"
"% HyperKING — quantum GAN for HSI restoration (IEEE TGRS 2025)\n"
"@article{lin2025hyperking,\n"
"  title={HyperKING: Quantum-Classical Generative Adversarial Networks for Hyperspectral Image Restoration},\n"
"  author={Lin, Chia-Hsiang and Young, Si-Sheng},\n"
"  journal={IEEE Transactions on Geoscience and Remote Sensing},\n"
"  year={2025},\n"
"  note={arXiv:2504.11782}\n"
"}\n"
"\n"
"% HQSAN — quantum self-attention for scene classification (J. Supercomputing 2025)\n"
"@article{hqsan2025,\n"
"  title={HQSAN: A Hybrid Quantum Self-Attention Network for Remote Sensing Image Scene Classification},\n"
"  journal={Journal of Supercomputing},\n"
"  year={2025}\n"
"}\n"
"\n"
"% QSCDNet — hybrid quantum change detection (IEEE TQE 2025)\n"
"@article{lv2025qscdnet,\n"
"  title={QSCDNet: A Hybrid Quantum Spectral Change Detection Network},\n"
"  author={Lv, Pengyuan and others},\n"
"  journal={IEEE Transactions on Quantum Engineering},\n"
"  year={2025}\n"
"}\n"
"\n"
"% HQViT — hybrid quantum vision transformer\n"
"@article{hqvit2025,\n"
"  title={HQViT: Hybrid Quantum Vision Transformer for Image Classification},\n"
"  note={arXiv:2504.02730},\n"
"  year={2025}\n"
"}\n"
"\n"
"% Barren plateaus\n"
"@article{mcclean2018barren,\n"
"  title={Barren Plateaus in Quantum Neural Network Training Landscapes},\n"
"  author={McClean, Jarrod R and others},\n"
"  journal={Nature Communications},\n"
"  year={2018}\n"
"}\n"
"\n"
"% PennyLane\n"
"@article{bergholm2018pennylane,\n"
"  title={PennyLane: Automatic Differentiation of Hybrid Quantum-Classical Computations},\n"
"  author={Bergholm, Ville and others},\n"
"  note={arXiv:1811.04968},\n"
"  year={2018}\n"
"}\n"
"\n"
"% Data encoding expressivity\n"
"@article{schuld2021encoding,\n"
"  title={Effect of data encoding on the expressive power of variational quantum-machine-learning models},\n"
"  author={Schuld, Maria and Sweke, Ryan and Meyer, Johannes Jakob},\n"
"  journal={Physical Review A},\n"
"  year={2021}\n"
"}\n"
"```\n"
"\n"
"---\n"
"\n"
"*This planning cell was generated in March 2026 as a comprehensive review and roadmap for the QHSA-Net research project targeting IEEE TGRS / IGARSS. Update this cell as experiments complete and new papers emerge.*\n"
)

with open('c:/Users/saika/Downloads/QHSA_Net_Research_Notebook_2.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

new_cell = {
    'cell_type': 'markdown',
    'metadata': {},
    'source': planning_content
}

nb['cells'].append(new_cell)

with open('c:/Users/saika/Downloads/QHSA_Net_Research_Notebook_2.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f'Done. Notebook now has {len(nb["cells"])} cells.')
print(f'Last cell type: {nb["cells"][-1]["cell_type"]}')
print(f'Planning cell length: {len(planning_content)} chars')
